### ISSUE TITLE
issue on the result

### ISSUE THREAD

**Issue by wtt0213** [mods333/energy-based-scene-graph#1]
Thanks for your working!
It seems that the MR and Zero-shot-MR of VCTREE-TDE in your paper are lower than the origin result in the work <Unbiased Scene Graph Generation from Biased Training>, can you explain this phenomenon?
Looking for your reply!

**Comment by mods333** [comment]
We use the official implementation of VCTREE-TDE to run experiments and obtain the results. We used the recommended configurations for the models and the results reported in the paper are the ones that we were able to reproduce. Also, the numbers are only lower in the case of PredCLS. For SGLCS the number we obtained for VCTree-TDE were higher than the numbers reported in the original paper and the SGDET numbers are comparable. The results for zero-shot are comparable with the numbers reported in the paper. Note that **we report zsR@20/50** whereas the VCTree-TDE paper reports **zsR@50/100**. If you compare the zsR@50 reported in our paper v.s. theirs then they are very similar.
