### ISSUE TITLE
GQA pretrained model?

### ISSUE THREAD

**Issue by Zhonghao2016** [mods333/energy-based-scene-graph#3]
Hello! Thanks for your brilliant work. Can you also please release the pretrained model on GQA? Thanks!

**Comment by mods333** [comment]
You can find the pretrained weights [here](https://csubcca-my.sharepoint.com/:u:/g/personal/suhail33_cs_ubc_ca/EdTRGRewfvBEqwmPaGb78LIB2pMaFWwhoKDgD3CJ6RKRhA?e=vYINpP). The code for the GQA data loader was on a different branch. I will merge it with the main branch once I get time.
