### ISSUE TITLE
TypeError: detection2graph() missing 2 required positional arguments: 'mode' and 'noise_var'

### ISSUE THREAD

**Issue by Nora-Zhang98** [mods333/energy-based-scene-graph#9]
## ❓ Questions and Help
hi dear author,
thanks for your excellent work, i am trying to reimplement your work but a bug occured:
![2021-12-22 11-20-37 的屏幕截图](https://user-images.githubusercontent.com/60804365/147030024-c4165195-45fa-4c3e-8f90-01f565346e6d.png)
the line with bug is in <energy_train_net.py> line 188:
pred_im_graph, pred_scene_graph, pred_bbox = detection2graph(images, detections, base_model, cfg.DATASETS.NUM_OBJ_CLASSES, mode)

but the definition of the function is :
def detection2graph(node_states, images, detections, base_model, num_obj_classes, mode, **_noise_var_**):
in <modeling/energy_head/utils.py>
it doesn't have a default value for  "noise_var"!

so i wonder how to deal with this bug
Hope for your help!thank you !

**Comment by mods333** [comment]
Looks like you are using `energy_train_net.py`. Could you instead use `energy_joint_train_cd.py` as in the README. I think that should fix the problem.

**Comment by Nora-Zhang98** [comment]
Finally i succeed to run the code! And to be honest, apex is too hard to use. I abandon it.

**Comment by Nora-Zhang98** [comment]
Oh it seems the last comment 4 days ago wasn't send successfully. I'd like to repeat it again: 
Dear author, thanks for your kind help!
